###########
# site.title

title:    'RL Cuphead'
subtitle: 'CS 175: Project in AI'
source: /docs


#########################
# more settings

markdown: kramdown
kramdown:
  math_engine: mathjax

exclude:
- README.md
- LICENSE.md
